 resource_group_name  = "idc-hack-rg"
 location = "East US"
 storage_account_name = "idc-hack-sa"
 account_tier="Standard"
 account_replication_type="LRS"
 container_name = "idc-hack-sc"
 container_access_type= "Private"
